defmodule DojoWeb.WeaveFragmentsTest do
  # Phase 2 — the locality fence (specs/groundwork.org gw-development).
  # Fragments are static text: they fetch RAW through the endpoint, untouched
  # by any server-side parsing. The client (weave/fragments.js) is the reader.
  use DojoWeb.ConnCase, async: true

  test "a fragment fetches raw through the static door", %{conn: conn} do
    conn = get(conn, "/codex/spirals.org")
    body = response(conn, 200)
    assert body =~ ":ID: frag-spiral"
    assert body =~ "#+BEGIN_SRC paperlang"
  end

  test "an unborn fragment is a plain 404 — the client renders the invitation" do
    conn = get(build_conn(), "/codex/a-fragment-waiting-to-be-born.org")
    assert conn.status == 404
  end

  test "the pressed index is the corpus's id→name map" do
    # Generated by scripts/press_codex_index.mjs (mix press.codex / assets.build).
    # Absent index is an honest degrade for the client; when pressed, spirals
    # must resolve: frag-spiral → spirals (the rename-healing the resolver needs).
    path = Path.join([:code.priv_dir(:dojo), "static", "codex", "index.json"])

    if File.exists?(path) do
      conn = get(build_conn(), "/codex/index.json")
      body = response(conn, 200)
      index = Jason.decode!(body)
      assert index["frag-spiral"]["name"] == "spirals"
      assert index["frag-roundness"]["name"] == "roundness"
    else
      # Not yet pressed in this environment — the door still 404s honestly.
      conn = get(build_conn(), "/codex/index.json")
      assert conn.status == 404
    end
  end
end
